//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFactory.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int AccountID { get; set; }
        public string AccountName { get; set; }
        public decimal Money { get; set; }
        public string Currency { get; set; }
        public Nullable<int> State { get; set; }
    }
}
