//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFactory.MODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class familylifeaccountEntities : DbContext
    {
        public familylifeaccountEntities()
            : base("name=familylifeaccountEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<cost> cost { get; set; }
        public virtual DbSet<costclass> costclass { get; set; }
        public virtual DbSet<earning> earning { get; set; }
        public virtual DbSet<earningclass> earningclass { get; set; }
        public virtual DbSet<hongling> hongling { get; set; }
        public virtual DbSet<monthcost> monthcost { get; set; }
        public virtual DbSet<navigation> navigation { get; set; }
        public virtual DbSet<persons> persons { get; set; }
        public virtual DbSet<seedoctor> seedoctor { get; set; }
        public virtual DbSet<shops> shops { get; set; }
        public virtual DbSet<view_companycostlist> view_companycostlist { get; set; }
        public virtual DbSet<view_costlist> view_costlist { get; set; }
        public virtual DbSet<view_earninglist> view_earninglist { get; set; }
        public virtual DbSet<view_honglinglist> view_honglinglist { get; set; }
        public virtual DbSet<view_shopslist> view_shopslist { get; set; }
    }
}
