//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFactory.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hongling
    {
        public int HonglingID { get; set; }
        public string HonglingName { get; set; }
        public System.DateTime AddTime { get; set; }
        public string HonglingContent { get; set; }
        public decimal HonglingMoney { get; set; }
        public int UserID { get; set; }
        public int AccountID { get; set; }
        public int IsDel { get; set; }
        public Nullable<int> EarningClassID { get; set; }
    }
}
