//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFactory.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class navigation
    {
        public int NavigationID { get; set; }
        public string Title { get; set; }
        public int ParentID { get; set; }
        public int Sort { get; set; }
        public string AssemblyPath { get; set; }
        public string Image { get; set; }
        public int IsShow { get; set; }
        public Nullable<int> IsCompany { get; set; }
    }
}
