//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFactory.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class shops
    {
        public int ShopID { get; set; }
        public string ShopName { get; set; }
        public int ParentID { get; set; }
        public string Address { get; set; }
        public int CostClassID { get; set; }
        public Nullable<int> IsCompany { get; set; }
    }
}
