//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFactory.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_companyearninglist
    {
        public int EarningID { get; set; }
        public string EarningName { get; set; }
        public System.DateTime AddTime { get; set; }
        public string EarningContent { get; set; }
        public decimal EarningMoney { get; set; }
        public int IsDel { get; set; }
        public Nullable<int> IsCompany { get; set; }
        public string CompanyName { get; set; }
        public string CompanyId { get; set; }
        public string ClassName { get; set; }
        public int EarningClassID { get; set; }
        public int ParentID { get; set; }
    }
}
