//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFactory.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_companycostlist
    {
        public string AccountName { get; set; }
        public string ShopName { get; set; }
        public string CostName { get; set; }
        public System.DateTime AddTime { get; set; }
        public decimal CostMoney { get; set; }
        public int IsDel { get; set; }
        public int ParentID { get; set; }
        public string ClassName { get; set; }
        public string CostContent { get; set; }
        public Nullable<int> IsCompany { get; set; }
    }
}
